--------------------------------------------------------
--  Constraints for Table B_BATCH
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."B_BATCH" MODIFY ("CD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_BATCH" ADD CONSTRAINT "PK_B_BATCH" PRIMARY KEY ("ID_BATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."B_BATCH" MODIFY ("ID_EXECUTION" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_BATCH" MODIFY ("ID_FILE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_BATCH" MODIFY ("ID_EXTRACT" NOT NULL ENABLE);
