--------------------------------------------------------
--  Constraints for Table B_FILE
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."B_FILE" MODIFY ("URI" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_FILE" ADD CONSTRAINT "PK_B_FILE" PRIMARY KEY ("ID_FILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."B_FILE" MODIFY ("FILENAME" NOT NULL ENABLE);
