--------------------------------------------------------
--  DDL for Table B_FILE
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."B_FILE" 
   (	"ID_FILE" NUMBER(*,0), 
	"FILENAME" VARCHAR2(500 CHAR), 
	"URI" VARCHAR2(500 CHAR) DEFAULT NULL, 
	"PATH" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
