--------------------------------------------------------
--  Constraints for Table B_LOAD_RECORD_ACTION
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."B_LOAD_RECORD_ACTION" MODIFY ("FL_VALID" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_LOAD_RECORD_ACTION" MODIFY ("CD_ACTION" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_LOAD_RECORD_ACTION" MODIFY ("ID_BATCH" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_LOAD_RECORD_ACTION" MODIFY ("ID_RECORD" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."B_LOAD_RECORD_ACTION" MODIFY ("ID_TABLE" NOT NULL ENABLE);
