--------------------------------------------------------
--  Constraints for Table BM_ADDRESS
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" ADD CONSTRAINT "PK_BM_ADDRESS" PRIMARY KEY ("ID_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("ID_ADDRESS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_ADDRESS" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
