--------------------------------------------------------
--  Constraints for Table BM_BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_BANK_ACCOUNT" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_BANK_ACCOUNT" ADD CONSTRAINT "PK_BM_BANK_ACCOUNT" PRIMARY KEY ("ID_BANK_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_BANK_ACCOUNT" MODIFY ("IBAN" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_BANK_ACCOUNT" MODIFY ("ID_BANK_ACCOUNT" NOT NULL ENABLE);
