--------------------------------------------------------
--  Constraints for Table BM_COMMISSION_SCHEME
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" ADD CONSTRAINT "PK_BM_COMMISSION_SCHEME" PRIMARY KEY ("ID_COMMISSION_SCHEME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("FL_RETAINED_AGENT_PREMIUM" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("FL_RETAINED_SPONSOR_PREMIUM" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("AGENT_PREMIUM_RATIO" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("SPONSOR_PREMIUM_RATIO" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("NET_PREMIUM_RATIO" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" MODIFY ("ID_COMMISSION_SCHEME" NOT NULL ENABLE);
