--------------------------------------------------------
--  Constraints for Table BM_COUNTRY
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" ADD CONSTRAINT "AK_UK_SHORT_CODE_BM_COUNT" UNIQUE ("SHORT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" ADD CONSTRAINT "AK_UK_CD_COUNTRY_BM_COUNT" UNIQUE ("CD_COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" ADD CONSTRAINT "PK_BM_COUNTRY" PRIMARY KEY ("ID_COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" MODIFY ("PHONE_AREA_CODE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" MODIFY ("SHORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" MODIFY ("CD_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_COUNTRY" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
