--------------------------------------------------------
--  DDL for Table BM_COUNTRY
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_COUNTRY" 
   (	"ID_COUNTRY" NUMBER(*,0), 
	"CD_COUNTRY" CHAR(3 CHAR), 
	"SHORT_CODE" CHAR(2 CHAR), 
	"PHONE_AREA_CODE" VARCHAR2(20 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE, 
	"COUNTRY_NAME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;

   COMMENT ON COLUMN "METSM_OWNER"."BM_COUNTRY"."CD_COUNTRY" IS '3-letter country code';
   COMMENT ON COLUMN "METSM_OWNER"."BM_COUNTRY"."SHORT_CODE" IS '2-letter country code';
   COMMENT ON COLUMN "METSM_OWNER"."BM_COUNTRY"."PHONE_AREA_CODE" IS 'Phone area code, e.g. +421';
