--------------------------------------------------------
--  Ref Constraints for Table BM_COMMISSION_SCHEME
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" ADD CONSTRAINT "FK_BM_COMMI_REFERENCE_BM_AGENT" FOREIGN KEY ("ID_AGENT")
	  REFERENCES "METSM_OWNER"."BM_AGENT" ("ID_AGENT") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" ADD CONSTRAINT "FK_BM_COMMI_REFERENCE_BM_PRODU" FOREIGN KEY ("ID_PRODUCT_VARIANT")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT_VARIANT" ("ID_PRODUCT_VARIANT") ENABLE;
