--------------------------------------------------------
--  DDL for Table BM_COMMISSION_SCHEME
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_COMMISSION_SCHEME" 
   (	"ID_COMMISSION_SCHEME" NUMBER(*,0), 
	"ID_AGENT" NUMBER(*,0), 
	"ID_PRODUCT_VARIANT" NUMBER(*,0), 
	"NET_PREMIUM_RATIO" NUMBER, 
	"SPONSOR_PREMIUM_RATIO" NUMBER, 
	"AGENT_PREMIUM_RATIO" NUMBER, 
	"FL_RETAINED_SPONSOR_PREMIUM" NUMBER(*,0) DEFAULT 0, 
	"FL_RETAINED_AGENT_PREMIUM" NUMBER(*,0) DEFAULT 0, 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
