--------------------------------------------------------
--  DDL for Table BM_LINE_OF_BUSINESS
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_LINE_OF_BUSINESS" 
   (	"ID_LINE_OF_BUSINESS" NUMBER(*,0), 
	"CD_LINE_OF_BUSINESS" VARCHAR2(50 CHAR), 
	"LINE_OF_BUSINESS_NAME" VARCHAR2(100 CHAR), 
	"LINE_OF_BUSINESS_NAME_SLOVAK" VARCHAR2(100 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
