--------------------------------------------------------
--  Ref Constraints for Table BM_PRODUCT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" ADD CONSTRAINT "FK_BM_PRODU_FK_PRODUC_BM_LINE_" FOREIGN KEY ("ID_LINE_OF_BUSINESS")
	  REFERENCES "METSM_OWNER"."BM_LINE_OF_BUSINESS" ("ID_LINE_OF_BUSINESS") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" ADD CONSTRAINT "FK_BM_PRODU_FK_PRODUC_BM_SPONS" FOREIGN KEY ("ID_SPONSOR")
	  REFERENCES "METSM_OWNER"."BM_SPONSOR" ("ID_SPONSOR") ENABLE;
