--------------------------------------------------------
--  Constraints for Table BM_PRODUCT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_CATEGORY" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_CATEGORY" ADD CONSTRAINT "PK_BM_PRODUCT_CATEGORY" PRIMARY KEY ("ID_PRODUCT_CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_CATEGORY" MODIFY ("PRODUCT_CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_CATEGORY" MODIFY ("ID_PRODUCT_CATEGORY" NOT NULL ENABLE);
