--------------------------------------------------------
--  Constraints for Table BM_PHONE_NUMBER
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PHONE_NUMBER" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PHONE_NUMBER" ADD CONSTRAINT "PK_PHONE_NUMBER" PRIMARY KEY ("ID_PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PHONE_NUMBER" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PHONE_NUMBER" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PHONE_NUMBER" MODIFY ("ID_PHONE_NUMBER" NOT NULL ENABLE);
