--------------------------------------------------------
--  Ref Constraints for Table BM_PRODUCT_VARIANT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT" ADD CONSTRAINT "FK_BM_PRODU_MODALITY_BM_MODAL" FOREIGN KEY ("ID_MODALITY")
	  REFERENCES "METSM_OWNER"."BM_MODALITY" ("ID_MODALITY") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT" ADD CONSTRAINT "FK_BM_PRODU_PRODUCT_BM_PRODU" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT" ("ID_PRODUCT") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT" ADD CONSTRAINT "FK_BM_PROD_VAR_BM_PROD_CAT" FOREIGN KEY ("ID_PRODUCT_CATEGORY")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT_CATEGORY" ("ID_PRODUCT_CATEGORY") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT" ADD CONSTRAINT "FK_BM_PROD_VAR_BM_PROD_TYPE" FOREIGN KEY ("ID_PRODUCT_TYPE")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT_TYPE" ("ID_PRODUCT_TYPE") ENABLE;
