--------------------------------------------------------
--  Constraints for Table BM_PRODUCT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" ADD CONSTRAINT "UQ_BM_PRODUCT_CD_PRODUCT" UNIQUE ("CD_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" ADD CONSTRAINT "PK_BM_PRODUCT" PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("POLICY_LAPSE_MONTH_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("ID_SPONSOR" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("ID_LINE_OF_BUSINESS" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT" MODIFY ("CD_PRODUCT" NOT NULL ENABLE);
