--------------------------------------------------------
--  DDL for Table BM_POLICY
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_POLICY" 
   (	"ID_POLICY" NUMBER(*,0), 
	"ID_STATUS" NUMBER(*,0), 
	"ID_PROPOSAL" NUMBER(*,0), 
	"ID_PARTY_INSURED" NUMBER(*,0), 
	"ID_PARTY_OWNER" NUMBER(*,0), 
	"ID_PRODUCT_VARIANT" NUMBER(*,0), 
	"ID_PHONE_NUMBER" NUMBER(*,0), 
	"ID_ADDRESS" NUMBER(*,0), 
	"POLICY_NUMBER" VARCHAR2(20 CHAR), 
	"DT_ISSUED" DATE, 
	"DT_START" DATE, 
	"DT_CLOSE" DATE, 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE, 
	"DT_PAIDTODATE" DATE, 
	"DT_LAST_TRANSACTION_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
