--------------------------------------------------------
--  DDL for Table BM_PRODUCT_VARIANT
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT" 
   (	"ID_PRODUCT_VARIANT" NUMBER(*,0), 
	"CD_PRODUCT_VARIANT" VARCHAR2(20 CHAR), 
	"ID_PRODUCT" NUMBER(*,0), 
	"ID_MODALITY" NUMBER(*,0), 
	"PRODUCT_VARIANT_NAME" VARCHAR2(100 CHAR), 
	"VALID_SINCE" DATE, 
	"VALID_UNTIL" DATE, 
	"ENTRY_AGE_LIMIT_LOW" NUMBER(*,0), 
	"ENTRY_AGE_LIMIT_HIGH" NUMBER(*,0) DEFAULT NULL, 
	"CD_EXTRACT_CODE" VARCHAR2(20 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE, 
	"ID_PRODUCT_TYPE" NUMBER(*,0), 
	"ID_PRODUCT_CATEGORY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
