--------------------------------------------------------
--  Ref Constraints for Table BM_POLICY
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_BM_POLIC_INSURED_BM_PARTY" FOREIGN KEY ("ID_PARTY_INSURED")
	  REFERENCES "METSM_OWNER"."BM_PARTY" ("ID_PARTY") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_BM_POLIC_OWNER_BM_PARTY" FOREIGN KEY ("ID_PARTY_OWNER")
	  REFERENCES "METSM_OWNER"."BM_PARTY" ("ID_PARTY") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_BM_POLIC_REFERENCE_BM_ADDRE" FOREIGN KEY ("ID_ADDRESS")
	  REFERENCES "METSM_OWNER"."BM_ADDRESS" ("ID_ADDRESS") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_BM_POLIC_REFERENCE_BM_PHONE" FOREIGN KEY ("ID_PHONE_NUMBER")
	  REFERENCES "METSM_OWNER"."BM_PHONE_NUMBER" ("ID_PHONE_NUMBER") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_BM_POLIC_STATUS_BM_STATU" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "METSM_OWNER"."BM_STATUS" ("ID_STATUS") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_POLICY" ADD CONSTRAINT "FK_POLICY_PRODUCT_VARIANT" FOREIGN KEY ("ID_PRODUCT_VARIANT")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT_VARIANT" ("ID_PRODUCT_VARIANT") ENABLE;
