--------------------------------------------------------
--  Constraints for Table BM_PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" MODIFY ("PRODUCT_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" ADD CONSTRAINT "AK_UK_CD_PRODUCT_TYPE_BM_PRODU" UNIQUE ("CD_PRODUCT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" ADD CONSTRAINT "PK_BM_PRODUCT_TYPE" PRIMARY KEY ("ID_PRODUCT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" MODIFY ("CD_PRODUCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_TYPE" MODIFY ("ID_PRODUCT_TYPE" NOT NULL ENABLE);
