--------------------------------------------------------
--  DDL for Table BM_PARTY
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_PARTY" 
   (	"ID_PARTY" NUMBER(*,0), 
	"ID_PARTY_TYPE" NUMBER(*,0), 
	"ID_GENDER" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(100 CHAR), 
	"LAST_NAME" VARCHAR2(100 CHAR), 
	"TITLE" VARCHAR2(10 CHAR), 
	"DT_BIRTH_DATE" DATE, 
	"BIRTH_NUMBER" VARCHAR2(10 CHAR), 
	"ICO" VARCHAR2(20 CHAR), 
	"FL_FOREIGNER" NUMBER(*,0), 
	"EMAIL" VARCHAR2(200 CHAR), 
	"COMPANY_NAME" VARCHAR2(100 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
