--------------------------------------------------------
--  DDL for Table BM_PRODUCT
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_PRODUCT" 
   (	"ID_PRODUCT" NUMBER(*,0), 
	"ID_LINE_OF_BUSINESS" NUMBER(*,0), 
	"ID_SPONSOR" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(200 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE, 
	"CD_PRODUCT" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"POLICY_LAPSE_MONTH_LIMIT" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
