--------------------------------------------------------
--  Ref Constraints for Table BM_PRODUCT_VARIANT_PLAN
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT_PLAN" ADD CONSTRAINT "FK_BM_PRODU_FK_PRODUC_BM_PLAN" FOREIGN KEY ("ID_PLAN")
	  REFERENCES "METSM_OWNER"."BM_PLAN" ("ID_PLAN") ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT_PLAN" ADD CONSTRAINT "FK_BM_PRODU_PRODUCT_V_BM_PRODU" FOREIGN KEY ("ID_PRODUCT_VARIANT")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT_VARIANT" ("ID_PRODUCT_VARIANT") ENABLE;
