--------------------------------------------------------
--  DDL for Table BM_PRODUCT_VARIANT_PLAN
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_PRODUCT_VARIANT_PLAN" 
   (	"ID_PRODUCT_VARIANT_PLAN" NUMBER(*,0), 
	"ID_PRODUCT_VARIANT" NUMBER(*,0), 
	"ID_PLAN" NUMBER(*,0), 
	"COVERAGE" NUMBER, 
	"PREMIUM" NUMBER, 
	"BAND" NUMBER, 
	"CX_RATE" FLOAT(10), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
