--------------------------------------------------------
--  DDL for Table BM_PLAN
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_PLAN" 
   (	"ID_PLAN" NUMBER(*,0), 
	"CD_PLAN" VARCHAR2(20 CHAR), 
	"PLAN_NAME" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
