--------------------------------------------------------
--  Constraints for Table BM_PARTY_TYPE
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_PARTY_TYPE" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PARTY_TYPE" ADD CONSTRAINT "AK_UK_CD_TYPE_PARTY_TY" UNIQUE ("CD_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PARTY_TYPE" ADD CONSTRAINT "PK_PARTY_TYPE" PRIMARY KEY ("ID_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_PARTY_TYPE" MODIFY ("CD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_PARTY_TYPE" MODIFY ("ID_TYPE" NOT NULL ENABLE);
