--------------------------------------------------------
--  Constraints for Table BM_SPONSOR
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" ADD CONSTRAINT "AK_UK_CD_SPONSOR_BM_SPONS" UNIQUE ("CD_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" ADD CONSTRAINT "PK_BM_SPONSOR" PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("IC_DPH" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("DIC" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("ICO" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("COMPANY_REGISTRATION" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("SPONSOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("CD_SPONSOR" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("ID_BANK_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_SPONSOR" MODIFY ("ID_SPONSOR" NOT NULL ENABLE);
