--------------------------------------------------------
--  Constraints for Table BM_STATUS
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."BM_STATUS" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_STATUS" ADD CONSTRAINT "AK_UK_CD_STATUS_STATUS" UNIQUE ("CD_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_STATUS" ADD CONSTRAINT "PK_STATUS" PRIMARY KEY ("ID_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."BM_STATUS" MODIFY ("STATUS_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_STATUS" MODIFY ("CD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."BM_STATUS" MODIFY ("ID_STATUS" NOT NULL ENABLE);
