--------------------------------------------------------
--  DDL for Table BM_SPONSOR
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."BM_SPONSOR" 
   (	"ID_SPONSOR" NUMBER(*,0), 
	"ID_BANK_ACCOUNT" NUMBER(*,0), 
	"CD_SPONSOR" VARCHAR2(20 CHAR), 
	"SPONSOR_NAME" VARCHAR2(200 CHAR), 
	"COMPANY_NAME" VARCHAR2(200 CHAR), 
	"COMPANY_REGISTRATION" VARCHAR2(1000 CHAR), 
	"ICO" VARCHAR2(50 CHAR), 
	"DIC" VARCHAR2(50 CHAR), 
	"IC_DPH" VARCHAR2(50 CHAR), 
	"DT_CREATED" DATE, 
	"DT_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
