--------------------------------------------------------
--  DDL for Table FROM_DWH_PLAN
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."FROM_DWH_PLAN" 
   (	"PLANKEY" NUMBER(10,0), 
	"PLANID" VARCHAR2(50 CHAR), 
	"SOURCESYSTEMKEY" NUMBER(10,0), 
	"COLLECTIONOFFICEKEY" NUMBER(10,0), 
	"LINEOFBUSINESSKEY" NUMBER(10,0), 
	"FINANCIALLINEOFBUSINESSKEY" NUMBER(10,0), 
	"MARKETINGCAMPAIGNKEY" NUMBER(10,0), 
	"TITLE" VARCHAR2(40 CHAR), 
	"TITLESLOVAK" VARCHAR2(40 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"DESCRIPTIONSLOVAK" VARCHAR2(255 CHAR), 
	"TECHNICALINTERESTRATE" NUMBER(38,2), 
	"LAUNCHDATE" VARCHAR2(10 CHAR), 
	"APPROVEDFLAG" NUMBER(10,0), 
	"APPROVEDFORCLAIMSFLAG" NUMBER(10,0), 
	"WAIVERFLAG" NUMBER(10,0), 
	"CHILDPROTECTIONAGREEMENTFLAG" NUMBER(10,0), 
	"ALLOWEDFORDYNAMIZATIONFLAG" NUMBER(10,0), 
	"COVERAGEAMOUNTMULTIPLIER" NUMBER(10,0), 
	"DELETEDFLAG" NUMBER(10,0), 
	"INSERTEDDATETIME" DATE, 
	"UPDATEDDATETIME" DATE, 
	"INSERTEDEXECUTIONID" NUMBER(38,0), 
	"UPDATEDEXECUTIONID" NUMBER(38,0), 
	"PLANSELLINGTYPEKEY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
