--------------------------------------------------------
--  Constraints for Table FROM_DWH_PLAN
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("PLANSELLINGTYPEKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("INSERTEDEXECUTIONID" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("INSERTEDDATETIME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("DELETEDFLAG" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("TITLESLOVAK" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("MARKETINGCAMPAIGNKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("FINANCIALLINEOFBUSINESSKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("LINEOFBUSINESSKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("COLLECTIONOFFICEKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("SOURCESYSTEMKEY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("PLANID" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."FROM_DWH_PLAN" MODIFY ("PLANKEY" NOT NULL ENABLE);
