--------------------------------------------------------
--  DDL for Table MD_APP_CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_APP_CONFIGURATION" 
   (	"ID_APP_CONFIGURATION" NUMBER(*,0), 
	"PROPERTY_NAME" VARCHAR2(100 CHAR), 
	"PROPERTY_VALUE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "METSM_OWNER_DATA" ;
