--------------------------------------------------------
--  Constraints for Table MD_APP_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_APP_CONFIGURATION" ADD CONSTRAINT "PK_APP_CONFIGURATION" PRIMARY KEY ("ID_APP_CONFIGURATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_APP_CONFIGURATION" MODIFY ("PROPERTY_VALUE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_APP_CONFIGURATION" MODIFY ("PROPERTY_NAME" NOT NULL ENABLE);
