--------------------------------------------------------
--  DDL for Table MD_DATA_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_DATA_ERROR_LOG" 
   (	"ID_DATA_ERROR_LOG" NUMBER(*,0), 
	"ID_BATCH" NUMBER(*,0), 
	"ID_EXTRACT" NUMBER(*,0), 
	"ID_DATA_CONTROL" NUMBER(*,0), 
	"ID_RECORD" NUMBER(*,0), 
	"DT_CREATED" DATE, 
	"ERROR_MSG" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
