--------------------------------------------------------
--  DDL for Table MD_DATA_CONTROL
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_DATA_CONTROL" 
   (	"ID_DATA_CONTROL" NUMBER(*,0), 
	"ID_EXTRACT" NUMBER(*,0), 
	"DATA_CONTROL_NAME" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"CMD" VARCHAR2(1000 CHAR), 
	"CD_ERROR" VARCHAR2(10 CHAR), 
	"ERROR_MSG" VARCHAR2(100 CHAR), 
	"FL_ACTIVE" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
