--------------------------------------------------------
--  Constraints for Table MD_DATA_CONTROL
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" ADD CONSTRAINT "PK_MD_DATA_CONTROL" PRIMARY KEY ("ID_DATA_CONTROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("FL_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("ERROR_MSG" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("CD_ERROR" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("CMD" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("DATA_CONTROL_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_DATA_CONTROL" MODIFY ("ID_DATA_CONTROL" NOT NULL ENABLE);
