--------------------------------------------------------
--  DDL for Table MD_EXTRACT_AUTH
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_EXTRACT_AUTH" 
   (	"ID_EXTRACT_AUTH" NUMBER(*,0), 
	"DOMAIN" VARCHAR2(50 CHAR) DEFAULT NULL, 
	"USERNAME" VARCHAR2(50 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "METSM_OWNER_DATA" ;
