--------------------------------------------------------
--  DDL for Table MD_EXTRACT
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_EXTRACT" 
   (	"ID_EXTRACT" NUMBER(*,0), 
	"EXTRACT_NAME" VARCHAR2(100 CHAR), 
	"ID_PRODUCT" NUMBER(*,0) DEFAULT NULL, 
	"FL_ACTIVE" NUMBER(*,0) DEFAULT 0, 
	"CD_EXTRACT" VARCHAR2(20 CHAR), 
	"SOURCE_URI" VARCHAR2(200 CHAR) DEFAULT NULL, 
	"ID_EXTRACT_AUTH" NUMBER(*,0), 
	"FILE_ENCODING" VARCHAR2(10 CHAR) DEFAULT 'UTF-8', 
	"FILE_NAME_PATTERN" VARCHAR2(200 CHAR) DEFAULT NULL, 
	"CSV_SEPARATOR" VARCHAR2(1 CHAR) DEFAULT ',', 
	"PARSER" VARCHAR2(200 CHAR) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
