--------------------------------------------------------
--  DDL for Table MD_EXTRACT_PROPERTY
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" 
   (	"ID_EXTRACT_PROPERTY" NUMBER(*,0), 
	"PROPERTY_NAME" VARCHAR2(50 CHAR) DEFAULT NULL, 
	"ID_EXTRACT" NUMBER(*,0), 
	"POSITION" NUMBER(*,0) DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"MANDATORY" NUMBER(*,0) DEFAULT 0, 
	"LENGTH" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
