--------------------------------------------------------
--  Constraints for Table MD_EXTRACT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("PARSER" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("FILE_NAME_PATTERN" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("CSV_SEPARATOR" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("FILE_ENCODING" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("SOURCE_URI" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("FL_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("CD_EXTRACT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" ADD CONSTRAINT "PK_MD_EXTRACT" PRIMARY KEY ("ID_EXTRACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("EXTRACT_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" MODIFY ("ID_EXTRACT" NOT NULL ENABLE);
