--------------------------------------------------------
--  Constraints for Table MD_EXTRACT_PROPERTY
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" MODIFY ("MANDATORY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" MODIFY ("PROPERTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" ADD CONSTRAINT "PK_MD_EXTRACT_PROPERTY" PRIMARY KEY ("ID_EXTRACT_PROPERTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" MODIFY ("ID_EXTRACT" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT_PROPERTY" MODIFY ("ID_EXTRACT_PROPERTY" NOT NULL ENABLE);
