--------------------------------------------------------
--  Ref Constraints for Table MD_EXTRACT
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" ADD CONSTRAINT "FK_MD_EXTRACT_BM_PRODUCT" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "METSM_OWNER"."BM_PRODUCT" ("ID_PRODUCT") ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_EXTRACT" ADD CONSTRAINT "FK_MD_EXTRACT_MD_EXTRACT_AUTH" FOREIGN KEY ("ID_EXTRACT_AUTH")
	  REFERENCES "METSM_OWNER"."MD_EXTRACT_AUTH" ("ID_EXTRACT_AUTH") ENABLE;
