--------------------------------------------------------
--  DDL for Table MD_PROCESS_LOG
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_PROCESS_LOG" 
   (	"ID_PROCESS_LOG" NUMBER(*,0), 
	"ID_PROCESS" NUMBER(*,0), 
	"ID_BATCH" NUMBER(*,0), 
	"PROCESS_NAME" VARCHAR2(100 CHAR), 
	"ACTION" VARCHAR2(30 CHAR), 
	"STATUS" VARCHAR2(10 CHAR), 
	"DT_START" DATE, 
	"DT_END" DATE, 
	"ERROR_MSG" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
