--------------------------------------------------------
--  Constraints for Table MD_PROCESS_LOG
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" ADD CONSTRAINT "PK_MD_PROCESS_LOG" PRIMARY KEY ("ID_PROCESS_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" MODIFY ("DT_START" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" MODIFY ("PROCESS_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" MODIFY ("ID_PROCESS" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_PROCESS_LOG" MODIFY ("ID_PROCESS_LOG" NOT NULL ENABLE);
