--------------------------------------------------------
--  Constraints for Table MD_TABLE
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."MD_TABLE" MODIFY ("FL_ENTITY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_TABLE" ADD CONSTRAINT "MD_TABLE_PK" PRIMARY KEY ("ID_TABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
  ALTER TABLE "METSM_OWNER"."MD_TABLE" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."MD_TABLE" MODIFY ("ID_TABLE" NOT NULL ENABLE);
