--------------------------------------------------------
--  DDL for Table MD_TABLE
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."MD_TABLE" 
   (	"ID_TABLE" NUMBER(*,0), 
	"TABLE_NAME" VARCHAR2(30 CHAR), 
	"FL_ENTITY" NUMBER(*,0) DEFAULT 0, 
	"ENTITY_NAME" VARCHAR2(30 CHAR), 
	"SEQUENCE_NAME" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
