--------------------------------------------------------
--  DDL for Table SK_TABLE
--------------------------------------------------------

  CREATE TABLE "METSM_OWNER"."SK_TABLE" 
   (	"ID_TABLE" NUMBER(*,0), 
	"CD_NATURAL_KEY" VARCHAR2(1000 CHAR), 
	"ID_SURROGATE_KEY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
