--------------------------------------------------------
--  Constraints for Table ST_RAW_PARSED_DATA
--------------------------------------------------------

  ALTER TABLE "METSM_OWNER"."ST_RAW_PARSED_DATA" MODIFY ("ID_RECORD" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."ST_RAW_PARSED_DATA" MODIFY ("ID_EXTRACT_PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "METSM_OWNER"."ST_RAW_PARSED_DATA" ADD CONSTRAINT "PK_ST_RAW_PARSED_DATA" PRIMARY KEY ("ID_RECORD", "ID_EXTRACT_PROPERTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA"  ENABLE;
