--------------------------------------------------------
--  DDL for Index AK_MD_SK_DEFINITION
--------------------------------------------------------

  CREATE UNIQUE INDEX "METSM_OWNER"."AK_MD_SK_DEFINITION" ON "METSM_OWNER"."MD_SK_DEFINITION" ("CD_NK", "ID_EXTRACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
