--------------------------------------------------------
--  DDL for Index AK_SK_TABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "METSM_OWNER"."AK_SK_TABLE" ON "METSM_OWNER"."SK_TABLE" ("ID_TABLE", "CD_NATURAL_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 166 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
