--------------------------------------------------------
--  DDL for Index AK_UK_SHORT_CODE_BM_COUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "METSM_OWNER"."AK_UK_SHORT_CODE_BM_COUNT" ON "METSM_OWNER"."BM_COUNTRY" ("SHORT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "METSM_OWNER_DATA" ;
