REM INSERTING into METSM_OWNER.BM_AGENT
SET DEFINE OFF;
Insert into METSM_OWNER.BM_AGENT (ID_AGENT,ID_BANK_ACCOUNT,AGENT_NAME,DT_CREATED,DT_UPDATED) values ('1','2','K FINANCE LIFE, spol. s r.o.',to_date('31.05.2016 11:55:33','DD.MM.RRRR HH24:MI:SS'),null);
