REM INSERTING into METSM_OWNER.BM_STATUS
SET DEFINE OFF;
Insert into METSM_OWNER.BM_STATUS (ID_STATUS,CD_STATUS,STATUS_NAME,DT_CREATED,DT_UPDATED) values ('1','PENDING','Čakajúca',to_date('12.05.2016 14:21:46','DD.MM.RRRR HH24:MI:SS'),null);
Insert into METSM_OWNER.BM_STATUS (ID_STATUS,CD_STATUS,STATUS_NAME,DT_CREATED,DT_UPDATED) values ('2','ACTIVE','Aktívna',to_date('12.05.2016 14:21:51','DD.MM.RRRR HH24:MI:SS'),null);
Insert into METSM_OWNER.BM_STATUS (ID_STATUS,CD_STATUS,STATUS_NAME,DT_CREATED,DT_UPDATED) values ('3','CLOSED','Zrušená',to_date('12.05.2016 14:22:09','DD.MM.RRRR HH24:MI:SS'),null);
