REM INSERTING into METSM_OWNER.MD_EXTRACT
SET DEFINE OFF;
Insert into METSM_OWNER.MD_EXTRACT (ID_EXTRACT,EXTRACT_NAME,ID_PRODUCT,FL_ACTIVE,CD_EXTRACT,SOURCE_URI,ID_EXTRACT_AUTH,FILE_ENCODING,FILE_NAME_PATTERN,CSV_SEPARATOR,PARSER) values ('1','Orange travel','1','1','ORG_TRAVEL','file:///home/nh/SponsorMarketing/sources/travel',null,'ISO-8859-2','.*\.csv$',';','csv');
Insert into METSM_OWNER.MD_EXTRACT (ID_EXTRACT,EXTRACT_NAME,ID_PRODUCT,FL_ACTIVE,CD_EXTRACT,SOURCE_URI,ID_EXTRACT_AUTH,FILE_ENCODING,FILE_NAME_PATTERN,CSV_SEPARATOR,PARSER) values ('14','Orange poistenie faktur','21','0','ORG_INVOICE','file:///home/nh/SponsorMarketing/sources/org_invoice',null,'ISO-8859-2','.*\.csv$',';','csv');
