REM INSERTING into METSM_OWNER.MD_ST_DEFINITION
SET DEFINE OFF;
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('3','1','POLICY_NUMBER','OLGCONOSK','10');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('4','1','CD_COUNTRY','substr(OLGCN, 1, 3)','20');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('5','1','PAYMENT_TYPE','substr(OLGCN, 4, 2)','30');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('6','1','ACTION_TYPE','case OLGACTTYPE 
                when ''03'' then ''CREATE''
                when ''04'' then ''UPDATE''
                when ''10'' then ''DELETE''
else OLGACTTYPE
end','40');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('7','1','PHONE_NUMBER','OLGPHONE','50');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('8','1','CD_EXTRACT_CODE','OLGPRODTYP ','60');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('9','1','TITLE','CASE
WHEN OLGVIP = ''1'' THEN OLGTITLE
ELSE NULL
END','70');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('10','1','FIRST_NAME','CASE
WHEN OLGVIP = ''1'' THEN OLGNAME
ELSE NULL
END','80');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('11','1','LAST_NAME','CASE
WHEN OLGVIP = ''1'' THEN OLGSURNAME
ELSE NULL
END','90');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('12','1','BIRTH_NUMBER','CASE
WHEN OLGVIP = ''1'' THEN REPLACE(OLGPERSID,''/'','''')
ELSE NULL
END','100');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('13','1','COMPANY_NAME','CASE
WHEN OLGVIP = ''2'' THEN OLGNAME
ELSE NULL
END','110');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('14','1','ICO','CASE
WHEN OLGVIP = ''2'' THEN OLGPERSID
ELSE NULL
END','120');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('15','1','DT_BIRTH_DATE','to_date(OLGBIRTHDT, ''YYYYMMDD'')','130');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('16','1','STREET','OLGSTREET','140');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('17','1','ZIP','OLGZIP','150');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('18','1','CITY','OLGCITI','160');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('19','1','DT_ISSUED','to_date(OLGENROLDT,''YYYYMMDDHH24MISS'')','170');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('20','1','DT_START','to_date(OLGEFFDT,''YYYYMMDDHH24MISS'')','180');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('21','1','DT_CLOSE','to_date(OLGCLOSEDT,''YYYYMMDD'')','190');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('22','1','PREMIUM','OLGPREMIUM','200');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('23','1','PARTY_TYPE','OLGVIP ','210');
Insert into METSM_OWNER.MD_ST_DEFINITION (ID_ST_DEFINITION,ID_EXTRACT,CD_PROPERTY,PROPERTY_DEFINITION,POSITION) values ('24','1','FL_FOREIGNER','case when OLGFOREIGN = ''N'' then 0
 when OLGFOREIGN = ''Y'' then 1
             else null        
        end','220');
