REM INSERTING into METSM_OWNER.MD_TABLE
SET DEFINE OFF;
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('1','BM_ADDRESS','1','ADDRESS','SEQ_BM_ADDRESS');
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('2','BM_ADDRESS_TYPE','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('3','BM_BANK_ACCOUNT','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('4','BM_COUNTRY','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('5','BM_GENDER','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('6','BM_LINE_OF_BUSINESS','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('7','BM_MODALITY','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('8','BM_PARTY','1','PARTY','SEQ_BM_PARTY');
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('9','BM_PARTY_TYPE','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('10','BM_PHONE_NUMBER','1','PHONE_NUMBER','SEQ_BM_PHONE_NUMBER');
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('11','BM_POLICY','1','POLICY','SEQ_BM_POLICY');
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('12','BM_PRODUCT','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('13','BM_PRODUCT_CATEGORY','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('14','BM_PRODUCT_TYPE','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('15','BM_PRODUCT_VARIANT','0',null,null);
Insert into METSM_OWNER.MD_TABLE (ID_TABLE,TABLE_NAME,FL_ENTITY,ENTITY_NAME,SEQUENCE_NAME) values ('16','BM_SPONSOR','0',null,null);
