--------------------------------------------------------
--  DDL for Trigger TRG_SEQ_MD_EXTRACT_AUTH
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "METSM_OWNER"."TRG_SEQ_MD_EXTRACT_AUTH" 
BEFORE INSERT ON METSM_OWNER.MD_EXTRACT_AUTH
FOR EACH ROW
BEGIN
	IF :new.ID_EXTRACT_AUTH IS NULL THEN
		SELECT SEQ_MD_EXTRACT_AUTH.nextval INTO :new.ID_EXTRACT_AUTH FROM DUAL;
	END IF;
END;
/
ALTER TRIGGER "METSM_OWNER"."TRG_SEQ_MD_EXTRACT_AUTH" ENABLE;
