--------------------------------------------------------
--  DDL for Trigger TRG_SEQ_BM_BANK_ACCOUNT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "METSM_OWNER"."TRG_SEQ_BM_BANK_ACCOUNT" 
BEFORE INSERT ON METSM_OWNER.BM_BANK_ACCOUNT
FOR EACH ROW
BEGIN
	IF :new.ID_BANK_ACCOUNT IS NULL THEN
		SELECT SEQ_BM_BANK_ACCOUNT.nextval INTO :new.ID_BANK_ACCOUNT FROM DUAL;
	END IF;
END;
/
ALTER TRIGGER "METSM_OWNER"."TRG_SEQ_BM_BANK_ACCOUNT" ENABLE;
