--------------------------------------------------------
--  DDL for Trigger TRG_SEQ_MD_EXTRACT_PROPERTY
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "METSM_OWNER"."TRG_SEQ_MD_EXTRACT_PROPERTY" 
BEFORE INSERT ON "METSM_OWNER"."MD_EXTRACT_PROPERTY"
FOR EACH ROW
BEGIN
	IF :new.ID_EXTRACT_PROPERTY IS NULL THEN
		SELECT SEQ_MD_EXTRACT_PROPERTY.nextval INTO :new.ID_EXTRACT_PROPERTY FROM DUAL;
	END IF;
END;
/
ALTER TRIGGER "METSM_OWNER"."TRG_SEQ_MD_EXTRACT_PROPERTY" ENABLE;
